version: '3.8'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    restart: always
    command:
      - --config=/etc/otelcol-contrib/config.yaml
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
#      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
#      - 55679:55679 # zpages extension
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
#    volumes:
#      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml

#  loki:
#    image: grafana/loki:latest
#    command: -config.file=/etc/loki/local-config.yaml
#    ports:
#      - "3100:3100"
#
#  tempo:
#    image: grafana/tempo:latest
#    command: [ "-config.file=/etc/tempo.yml" ]
#    volumes:
#      - ./tempo.yml:/etc/tempo.yml
#    ports:
#      - "3200:3200"   # tempo
#      - "4318"  # otlp http