spring:
  application:
    name: last-day-of-training
  datasource:
    url: jdbc:mysql://localhost:3306/training
    username: root
    password: root123
  jpa:
    show-sql: true
server:
  port: 8080