version: '3.7'
services:
  weather-api:
    image: weather-api:1.0
    container_name: weather-api
    build:
      context: ./weather-api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9094
      - DATASOURCE_URL=jdbc:mysql://weather-mysql:3309/training
    depends_on:
      - weather-mysql
  weather-finder:
    image: weather-finder:1.0
    container_name: weather-finder
    build:
      context: ./weather-finder
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9094
      - DATASOURCE_URL=jdbc:mysql://weather-mysql:3309/training
    depends_on:
      - weather-mysql
  weather-mysql:
      image: mysql:8
      container_name: weather-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - 3309:3306
      volumes:
        - ./weather-mysql:/docker-entrypoint-initdb.d
